### PR TITLE
Create What-Is-and-how-to-use-GitHub

### PR DESCRIPTION
**Pull request by hjsohn**
SEcond
@mlee16 
@Sunguook 
@kimericd 
@danisoul

### CODE REVIEW

**Comment by kimericd** [comment]
I think this GitHub helps to enhance the way of communicating with developers!

**Comment by mlee16** [comment]
This is very helpful. Thank you for this!

**Comment by Sunguook** [comment]
:+1: :100:

**Comment by danisoul** [comment]
Thanks chief for initiating this wonderful collaboration! Yayeeaaa

**Comment by hjsohn** [comment]
@peterbell I cannot see the picture and link that I put the codes on my file. Can you let me know why it is not working?? Thanks!

**Comment by hjsohn** [comment]
Leave a comment

**Pull request merged**
