### PR TITLE
Create Quintessence_of_Agile_development.md

### PR DESCRIPTION
**Pull request by danisoul**
@hjsohn 
@Sunguook 
@kimericd 
@mlee16 

Please add any comments. Thanks team! You guys are great :smile:

### CODE REVIEW

**Comment by hjsohn** [comment]
:+1:

**Comment by hjsohn** [comment]
Keep doing!

**Comment by kimericd** [comment]
Great! how to structure the adaptive planning is essential!.

**Comment by mlee16** [comment]
Thanks for taking the initiative on this topic. This is great Dan!

**Comment by Sunguook** [comment]
:smile: It's great.

**Comment by danisoul** [comment]
Thanks guys! Collaboration makes perfect, agile makes it easy with style! :+1:

**Pull request merged**
