### PR TITLE
Hiring best programmers

### PR DESCRIPTION
**Pull request by mlee16**
@hjsohn 
@Sunguook 
@kimericd 
@danisoul 

Feel free to add any comments, we can talk more about compensations to lure best programmers.

### CODE REVIEW

**Comment by hjsohn** [comment]
Very good!  :+1::muscle::eyes:

**Comment by kimericd** [comment]
Furthermore, we also need to think thoroughly of retaining these "premium" developers

**Comment by mlee16** [comment]
I'll take that advice @hjsohn Thank you for your feedback! It's really helpful.

**Comment by mlee16** [comment]
That's also important too. Thanks @kimericd I appreciate it.

**Comment by danisoul** [comment]
I think Matt has highlighted the most important aspect in forming a team of programmers: culture and fun. In my experience as a CEO of a mobile games studio, I learned this the hard way and had to let go my senior programmer due to fundamental differences in perspectives, interests, and attitude. Thanks Matt, great job! :100:

**Comment by mlee16** [comment]
Thank you for sharing your experiences with us! @danisoul

**Pull request merged**
